# This file was generated by GoReleaser. DO NOT EDIT.
cask "tickerbox-cli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "81bdb84ccb5c78272a4f8df3e97b2c7cf58dea4f3a36e6f75e9f710763ed3cd8"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "176db69a6ff31384f1434d380549ca5ac4cf699628c0f9f711a882a6c243ad5c"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39b3ed11b037ca52ed32c9111513c7eac879f6fdbfd7f25becc80a84f5ad6bde"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdff2de47f5388a27a7c779bfd1d6c3b947a3e69588d79ca6a05a7fde3f7249e"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tickerbox-cli"
  desc "Command-line client for a TickerBox device's REST API."
  homepage "https://github.com/openbunny/tickerbox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tickerbox"

  # No zap stanza required
end
