# This file was generated by GoReleaser. DO NOT EDIT.
cask "tickerbox-cli" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "085e10cae451588fdb99edc06c477a3c586615cdceec7b66a16f7854a3c8de4f"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cacae9132bbbdbc957e4201d0d2e9661ba8ba78bc97f90a72c867013c22fe04"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6fc0ad87152112ba32dc910aeef4b1ef2c213c5e1c61201f09dc5c7e34819466"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d258de8002d1f759c503a461114c3ea94cd7eae3a5318bbd3e7a8a741cad332"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tickerbox-cli"
  desc "Command-line client for a TickerBox device's REST API."
  homepage "https://github.com/openbunny/tickerbox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tickerbox"

  # No zap stanza required
end
