# This file was generated by GoReleaser. DO NOT EDIT.
cask "tickerbox-cli" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "6556fac1af452b79617aef4101711f2e5f50227cf839e8a5fc1aec5c7902d593"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5eb72c22e3b6f4fd15d81acebf11eb8f41d1e01229a6bd9ee9affd8e635ef40f"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "366b40c0515c4c72e479e08c70f862c16c3a21e9e177e92a371ff630cf59d2f6"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9f45cc3bf437841c8adf810c6493159c71c4a41bd9a6873559264b675905ea9"
      url "https://github.com/openbunny/tickerbox-cli/releases/download/v#{version}/tickerbox-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tickerbox-cli"
  desc "Command-line client for a TickerBox device's REST API."
  homepage "https://github.com/openbunny/tickerbox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tickerbox"

  # No zap stanza required
end
