# This file was generated by GoReleaser. DO NOT EDIT.
cask "wormswmd" do
  depends_on arch: :arm64

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "61f7043fde4cf08823b95bf6b4d0ef27266f9de972e24116588b5320fe1d7c88"
      url "https://github.com/openbunny/wormswmd/releases/download/v#{version}/wormswmd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "wormswmd"
  desc "Patches Worms W.M.D so the game opens again"
  homepage "https://github.com/openbunny/wormswmd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wormswmd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/wormswmd"]
    end
  end

  # No zap stanza required
end
